//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRJ_WAREHOUSE_BIVN.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRJ_WAREHOUSE_BIVN.Resources.Views.Import.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bên nhập trước.
        /// </summary>
        public static string Bennhaptruoc {
            get {
                return ResourceManager.GetString("Bennhaptruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string Bophan {
            get {
                return ResourceManager.GetString("Bophan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí chung.
        /// </summary>
        public static string Chiphichung {
            get {
                return ResourceManager.GetString("Chiphichung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí cố định.
        /// </summary>
        public static string chiphicodinh {
            get {
                return ResourceManager.GetString("chiphicodinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string chitiet {
            get {
                return ResourceManager.GetString("chitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string chon {
            get {
                return ResourceManager.GetString("chon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển kho.
        /// </summary>
        public static string chuyenkho {
            get {
                return ResourceManager.GetString("chuyenkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí biến đổi theo sản lượng.
        /// </summary>
        public static string cpbiendoitheosanluong {
            get {
                return ResourceManager.GetString("cpbiendoitheosanluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt.
        /// </summary>
        public static string daduyet {
            get {
                return ResourceManager.GetString("daduyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đảm nhiệm.
        /// </summary>
        public static string Damnhiem {
            get {
                return ResourceManager.GetString("Damnhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang đợi.
        /// </summary>
        public static string dangdoi {
            get {
                return ResourceManager.GetString("dangdoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Dangky {
            get {
                return ResourceManager.GetString("Dangky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string danhmuc {
            get {
                return ResourceManager.GetString("danhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã sử dụng.
        /// </summary>
        public static string dasudung {
            get {
                return ResourceManager.GetString("dasudung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string dathang {
            get {
                return ResourceManager.GetString("dathang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string denngay {
            get {
                return ResourceManager.GetString("denngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm giao hàng.
        /// </summary>
        public static string Diadiemgiaohang {
            get {
                return ResourceManager.GetString("Diadiemgiaohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện giao hàng.
        /// </summary>
        public static string Dieukiengiaohang {
            get {
                return ResourceManager.GetString("Dieukiengiaohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi sang USD.
        /// </summary>
        public static string doisangusd {
            get {
                return ResourceManager.GetString("doisangusd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá ước tính.
        /// </summary>
        public static string Dongiauoctinh {
            get {
                return ResourceManager.GetString("Dongiauoctinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý bởi.
        /// </summary>
        public static string dongyboi {
            get {
                return ResourceManager.GetString("dongyboi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string Donvi {
            get {
                return ResourceManager.GetString("Donvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị chi tiết.
        /// </summary>
        public static string Donvichitiet {
            get {
                return ResourceManager.GetString("Donvichitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị quy đổi.
        /// </summary>
        public static string donviquydoi {
            get {
                return ResourceManager.GetString("donviquydoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng.
        /// </summary>
        public static string Dung {
            get {
                return ResourceManager.GetString("Dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Được tách từ.
        /// </summary>
        public static string Duoctachtu {
            get {
                return ResourceManager.GetString("Duoctachtu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gấp.
        /// </summary>
        public static string Gap {
            get {
                return ResourceManager.GetString("Gap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Ghichu {
            get {
                return ResourceManager.GetString("Ghichu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tiền.
        /// </summary>
        public static string Giatien {
            get {
                return ResourceManager.GetString("Giatien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu.
        /// </summary>
        public static string guiyeucau {
            get {
                return ResourceManager.GetString("guiyeucau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng ngoài danh mục.
        /// </summary>
        public static string hangngoaidanhmuc {
            get {
                return ResourceManager.GetString("hangngoaidanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng trong danh mục.
        /// </summary>
        public static string hangtrongdanhmuc {
            get {
                return ResourceManager.GetString("hangtrongdanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        public static string hanhdong {
            get {
                return ResourceManager.GetString("hanhdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Lịch sử nhập.
        /// </summary>
        public static string Idlichsu {
            get {
                return ResourceManager.GetString("Idlichsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        public static string Kho {
            get {
                return ResourceManager.GetString("Kho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối.
        /// </summary>
        public static string Khoi {
            get {
                return ResourceManager.GetString("Khoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho nhập về.
        /// </summary>
        public static string khonhapve {
            get {
                return ResourceManager.GetString("khonhapve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string Loai {
            get {
                return ResourceManager.GetString("Loai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chi phí.
        /// </summary>
        public static string loaichiphi {
            get {
                return ResourceManager.GetString("loaichiphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hàng.
        /// </summary>
        public static string loaihang {
            get {
                return ResourceManager.GetString("loaihang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình tờ khai.
        /// </summary>
        public static string loaihinhtokhai {
            get {
                return ResourceManager.GetString("loaihinhtokhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phiếu.
        /// </summary>
        public static string loaiphieu {
            get {
                return ResourceManager.GetString("loaiphieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tiền.
        /// </summary>
        public static string loaitien {
            get {
                return ResourceManager.GetString("loaitien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log nhập - xuất.
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượng hàng làm thủ tục hải quan.
        /// </summary>
        public static string Luonglamthutuc {
            get {
                return ResourceManager.GetString("Luonglamthutuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượng thực tế về kho.
        /// </summary>
        public static string Luongthucte {
            get {
                return ResourceManager.GetString("Luongthucte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượng về kho đã nhập.
        /// </summary>
        public static string luongvekho {
            get {
                return ResourceManager.GetString("luongvekho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng.
        /// </summary>
        public static string Mahang {
            get {
                return ResourceManager.GetString("Mahang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hệ thống.
        /// </summary>
        public static string Mahethong {
            get {
                return ResourceManager.GetString("Mahethong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kế toán.
        /// </summary>
        public static string Maketoan {
            get {
                return ResourceManager.GetString("Maketoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Manhanvien {
            get {
                return ResourceManager.GetString("Manhanvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nguyên vật liệu.
        /// </summary>
        public static string MaNVL {
            get {
                return ResourceManager.GetString("MaNVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string Masanpham {
            get {
                return ResourceManager.GetString("Masanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã yêu cầu.
        /// </summary>
        public static string mayeucau {
            get {
                return ResourceManager.GetString("mayeucau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        public static string moi {
            get {
                return ResourceManager.GetString("moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục đích.
        /// </summary>
        public static string Mucdich {
            get {
                return ResourceManager.GetString("Mucdich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giao hàng dự kiến.
        /// </summary>
        public static string ngaygiaohangdukien {
            get {
                return ResourceManager.GetString("ngaygiaohangdukien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhập kho.
        /// </summary>
        public static string Ngaynhapkho {
            get {
                return ResourceManager.GetString("Ngaynhapkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày yêu cầu.
        /// </summary>
        public static string Ngayyeucau {
            get {
                return ResourceManager.GetString("Ngayyeucau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại tệ.
        /// </summary>
        public static string Ngoaite {
            get {
                return ResourceManager.GetString("Ngoaite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dự thảo.
        /// </summary>
        public static string nguoiduthao {
            get {
                return ResourceManager.GetString("nguoiduthao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận.
        /// </summary>
        public static string nguoinhan {
            get {
                return ResourceManager.GetString("nguoinhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhập kho.
        /// </summary>
        public static string Nguoinhapkho {
            get {
                return ResourceManager.GetString("Nguoinhapkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người phê duyệt.
        /// </summary>
        public static string nguoipheduyet {
            get {
                return ResourceManager.GetString("nguoipheduyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string nguoitao {
            get {
                return ResourceManager.GetString("nguoitao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người thẩm tra.
        /// </summary>
        public static string nguoithamtra {
            get {
                return ResourceManager.GetString("nguoithamtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người xuất kho.
        /// </summary>
        public static string nguoixuatkho {
            get {
                return ResourceManager.GetString("nguoixuatkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string nhacungcap {
            get {
                return ResourceManager.GetString("nhacungcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận hàng theo PO.
        /// </summary>
        public static string nhanhangtheoPO {
            get {
                return ResourceManager.GetString("nhanhangtheoPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        public static string Nhapkho {
            get {
                return ResourceManager.GetString("Nhapkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập PO Number.
        /// </summary>
        public static string NhapPO {
            get {
                return ResourceManager.GetString("NhapPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string Nhom {
            get {
                return ResourceManager.GetString("Nhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string Noidung {
            get {
                return ResourceManager.GetString("Noidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi giao hàng dự kiến.
        /// </summary>
        public static string noigiaohangdukien {
            get {
                return ResourceManager.GetString("noigiaohangdukien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu nhận hàng theo PO.
        /// </summary>
        public static string phieunhanhang {
            get {
                return ResourceManager.GetString("phieunhanhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string Phongban {
            get {
                return ResourceManager.GetString("Phongban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban yêu cầu.
        /// </summary>
        public static string phongbanyeucau {
            get {
                return ResourceManager.GetString("phongbanyeucau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng chịu phí.
        /// </summary>
        public static string phongchiuphi {
            get {
                return ResourceManager.GetString("phongchiuphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng tiếp nhận.
        /// </summary>
        public static string phongtiepnhan {
            get {
                return ResourceManager.GetString("phongtiepnhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức vận chuyển.
        /// </summary>
        public static string Phuongthucvanchuyen {
            get {
                return ResourceManager.GetString("Phuongthucvanchuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nguyên vật liệu.
        /// </summary>
        public static string QuanlyNVL {
            get {
                return ResourceManager.GetString("QuanlyNVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        public static string Quyen {
            get {
                return ResourceManager.GetString("Quyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string soluong {
            get {
                return ResourceManager.GetString("soluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng Order.
        /// </summary>
        public static string soluongdathang {
            get {
                return ResourceManager.GetString("soluongdathang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số PO.
        /// </summary>
        public static string Sopo {
            get {
                return ResourceManager.GetString("Sopo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string Sotien {
            get {
                return ResourceManager.GetString("Sotien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Sua {
            get {
                return ResourceManager.GetString("Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản cố định.
        /// </summary>
        public static string taisancodinh {
            get {
                return ResourceManager.GetString("taisancodinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng bằng tiếng Anh/Nhật.
        /// </summary>
        public static string TenhangTA {
            get {
                return ResourceManager.GetString("TenhangTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng bằng tiếng Việt.
        /// </summary>
        public static string TenhangTV {
            get {
                return ResourceManager.GetString("TenhangTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên mã kế toán.
        /// </summary>
        public static string TenMaketoan {
            get {
                return ResourceManager.GetString("TenMaketoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string Tennhanvien {
            get {
                return ResourceManager.GetString("Tennhanvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nguyên vật liệu.
        /// </summary>
        public static string TenNVL {
            get {
                return ResourceManager.GetString("TenNVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng yêu cầu.
        /// </summary>
        public static string tenphongyeucau {
            get {
                return ResourceManager.GetString("tenphongyeucau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string thanhtien {
            get {
                return ResourceManager.GetString("thanhtien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dòng mới.
        /// </summary>
        public static string themdongmoi {
            get {
                return ResourceManager.GetString("themdongmoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian nhận về.
        /// </summary>
        public static string thoigiannhanve {
            get {
                return ResourceManager.GetString("thoigiannhanve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn muốn nhận .
        /// </summary>
        public static string thoihanmuonnhan {
            get {
                return ResourceManager.GetString("thoihanmuonnhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn thanh toán.
        /// </summary>
        public static string thoihanthanhtoan {
            get {
                return ResourceManager.GetString("thoihanthanhtoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông thường.
        /// </summary>
        public static string Thongthuong {
            get {
                return ResourceManager.GetString("Thongthuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc đơn yêu cầu.
        /// </summary>
        public static string thuocdonyeucau {
            get {
                return ResourceManager.GetString("thuocdonyeucau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string timkiem {
            get {
                return ResourceManager.GetString("timkiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng đơn.
        /// </summary>
        public static string Tinhtrangdon {
            get {
                return ResourceManager.GetString("Tinhtrangdon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng hải quan.
        /// </summary>
        public static string tinhtranghaiquan {
            get {
                return ResourceManager.GetString("tinhtranghaiquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng tờ khai.
        /// </summary>
        public static string tinhtrangtokhai {
            get {
                return ResourceManager.GetString("tinhtrangtokhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối đa.
        /// </summary>
        public static string Toida {
            get {
                return ResourceManager.GetString("Toida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối thiểu.
        /// </summary>
        public static string Toithieu {
            get {
                return ResourceManager.GetString("Toithieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng đơn.
        /// </summary>
        public static string tongdon {
            get {
                return ResourceManager.GetString("tongdon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho.
        /// </summary>
        public static string tonkho {
            get {
                return ResourceManager.GetString("tonkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đơn.
        /// </summary>
        public static string Trangthaidon {
            get {
                return ResourceManager.GetString("Trangthaidon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập lần cuối.
        /// </summary>
        public static string Truycap {
            get {
                return ResourceManager.GetString("Truycap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string Tuchoi {
            get {
                return ResourceManager.GetString("Tuchoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày .
        /// </summary>
        public static string Tungay {
            get {
                return ResourceManager.GetString("Tungay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá.
        /// </summary>
        public static string tygia {
            get {
                return ResourceManager.GetString("tygia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT(%).
        /// </summary>
        public static string vat {
            get {
                return ResourceManager.GetString("vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string vitri {
            get {
                return ResourceManager.GetString("vitri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận nhập kho.
        /// </summary>
        public static string xacnhannhapkho {
            get {
                return ResourceManager.GetString("xacnhannhapkho", resourceCulture);
            }
        }
    }
}
